name: Download Files and Commit

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 5"

env:
  OUTPUT_DIRECTORY: output
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write

jobs:
  download_and_commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Create output directory
      run: |
        mkdir -p $OUTPUT_DIRECTORY
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-interaction --no-ansi
    - name: Run Python script
      run: python step01_download_hl.py $OUTPUT_DIRECTORY/step01.csv
    - name: Commit changes
      run: |        
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -f $OUTPUT_DIRECTORY/*
        git commit -m "Automated download and commit - step01"
        git push -f